name: Deploy app

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      uses: adrielcodeco/docker-compose-run-action@v1
      with:
        compose-file: './docker-compose.ci.yml'
        service: builder
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: telegram-quiz-bot
        path: bot/app/telegram-quiz-bot

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create host key
      env:
        KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$KEY" > id_ed25519
        chmod 0600 id_ed25519
    - name: Pull master branch
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        PORT: ${{ secrets.DEPLOY_PORT }}
        USER: ${{ secrets.DEPLOY_USER }}
      run: >
        ssh -o StrictHostKeyChecking=no -i id_ed25519 $USER@$HOST -p $PORT
        'cd ~/telegram-quiz-bot-prod &&
        git checkout master &&
        git pull &&
        docker-compose restart bot'
    - name: Remove host key
      run: rm id_ed25519
