name: Deploy documentation

on:
  push:
    branches:
      - dev

jobs:
  deploy-godoc:
    runs-on: ubuntu-latest
    steps:
    - name: Pull dev branch
      uses: cross-the-world/ssh-pipeline@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        pass: ${{ secrets.DEPLOY_PASS }}
        port: ${{ secrets.DEPLOY_PORT }}
        connect_timeout: 10s
        script: |
          cd ~/telegram-quiz-bot
          git checkout dev
          git pull
          docker-compose -f ./docker-compose.ci.yml stop godoc
          docker-compose -f ./docker-compose.ci.yml up -d --build godoc
