name: Deploy documentation

on:
  push:
    branches:
      - dev

jobs:
  deploy-godoc:
    runs-on: ubuntu-latest
    steps:
    - name: Pull dev branch
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          cd ~/telegram-quiz-bot
          git checkout dev
          git pull
          docker-compose -f ./docker-compose.ci.yml stop godoc
          docker-compose -f ./docker-compose.ci.yml up -d --build godoc
