name: Test

on:
  push:
    branches:
      - "dev"
      - "feature/**"
      - "fix/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Lint
      uses: adrielcodeco/docker-compose-run-action@v1
      with:
        compose-file: './docker-compose.ci.yml'
        service: linter

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run unit tests
      uses: adrielcodeco/docker-compose-run-action@v1
      with:
        compose-file: './docker-compose.ci.yml'
        service: unit-tester

  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run integration tests
      uses: adrielcodeco/docker-compose-run-action@v1
      with:
        compose-file: './docker-compose.ci.yml'
        service: integration-tester

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      uses: adrielcodeco/docker-compose-run-action@v1
      with:
        compose-file: './docker-compose.ci.yml'
        service: builder
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: telegram-quiz-bot
        path: bot/app/telegram-quiz-bot
