name: Test

on:
  push:
    branches:
      - "dev"
      - "feature/**"
      - "fix/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: docker compose -f ./docker-compose.ci.yml run -T linter

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run unit tests
      run: docker compose -f ./docker-compose.ci.yml run -T unit-tester

  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run integration tests
      run: docker compose -f ./docker-compose.ci.yml run -T integration-tester

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: docker compose -f ./docker-compose.ci.yml run -T builder

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: telegram-quiz-bot
        path: bot/app/telegram-quiz-bot
